"2015 Columbia College Student Council":
  facebook: "257020914343135"
"2016 Columbia College Student Council":
  facebook: "414584481937511"
"Activities Board at Columbia":
  facebook: "717330888294259"
"African Students Association, Columbia University":
  facebook: "320800730384"
"Application Development Initiative":
  facebook: "263741120328412"
"Art of Living Club Columbia University":
  facebook: "520769028008386"
"BOSS Barnard Organization of Soul Sisters":
  facebook: "124263327769732"
"Bacchanal - Columbia University":
  facebook: "546415562042239"
"Barnard Honor Board":
  facebook: "129362477239648"
"Beta Theta Pi - Columbia University":
  facebook: "127184634043594"
"Black Theatre Ensemble":
  facebook: "153912894629817"
"CCK (Compass Christian Koinonia)":
  facebook: "174906829249234"
"CISA: Columbia Iranian Students Association":
  facebook: "1375421566064564"
"CU Artist Society":
  facebook: "428445673869676"
"CU Asian Pacific American Heritage Month - APAHM":
  facebook: "375683145895890"
"CU Generation":
  facebook: "185837218150459"
"CU Hindu Students Organization - HSO":
  facebook: "179902808839135"
"CU Players":
  facebook: "447542345306004"
"CUCSSA":
  facebook: "36845738820"
"CUPID-Columbia University Partnership for International Development":
  facebook: "53952926627"
"Chicano Caucus":
  facebook: "479184565457877"
"Chowdah Sketch Comedy":
  facebook: "324052140074"
"Clefhangers":
  facebook: "83038617978"
"College Democrats of Columbia College":
  facebook: "1506111726297876"
"Columbia Bach Society":
  facebook: "167922473231554"
"Columbia Biomedical Engineering Society":
  facebook: "635929716473961"
"Columbia Business School":
  facebook: "42316303783"
"Columbia Business School Private Equity & Venture Capital Club":
  facebook: "430266570364398"
"Columbia China Law and Business Association (CCLBA)":
  facebook: "238971376152821"
"Columbia Classical Performers":
  facebook: "157090571531"
"Columbia College Student Council 2017":
  facebook: "402055506589690"
"Columbia Cricket Club":
  facebook: "347132252065025"
"Columbia Culinary Society":
  facebook: "300490753472246"
"Columbia Daily Spectator":
  facebook: "58365309913"
"Columbia Data Science Society":
  facebook: "230719923749613"
"Columbia EcoReps":
  facebook: "142451429189053"
"Columbia Economics Society":
  facebook: "406947596037547"
"Columbia Elections Board":
  facebook: "656632027711940"
"Columbia Engineering":
  facebook: !!null
"Columbia Engineering Student Council":
  facebook: "160722737377300"
"Columbia Engineering Student Council 2015":
  facebook: "324293917585042"
"Columbia Entrepreneurs Organization":
  facebook: "235600359819546"
"Columbia Financial Investment Group - CFIG":
  facebook: "162282307296224"
"Columbia Financial Review - CFR":
  facebook: "469888179740276"
"Columbia GSAPP":
  facebook: "112971615402197"
"Columbia Graduate Consulting Club":
  facebook: "249997198467774"
"Columbia International Relations Council and Association - CIRCA":
  facebook: "682327028452194"
"Columbia Journal of Literary Criticism":
  facebook: "514326122022170"
"Columbia Journalism School":
  facebook: "13795941507"
"Columbia Korean Students Association":
  facebook: "124968174239226"
"Columbia Law School":
  facebook: "109409079078868"
"Columbia Mock Trial":
  facebook: "121797624536702"
"Columbia Organization of Rising Entrepreneurs (CORE)":
  facebook: "111534465576828"
"Columbia Photography Association":
  facebook: "468304949948202"
"Columbia Political Review":
  facebook: "144759108874404"
"Columbia PorColombia":
  facebook: "418333818220378"
"Columbia Pre-Law Society":
  facebook: "114734471960135"
"Columbia Prison Divest":
  facebook: "1376345619301146"
"Columbia Public Health":
  facebook: "141764905854299"
"Columbia Raas":
  facebook: "124759657624046"
"Columbia Science Review":
  facebook: "281550855210083"
"Columbia Student Global AIDS Campaign":
  facebook: "331138486940025"
"Columbia Students for International Service":
  facebook: "500742816684283"
"Columbia Students for Justice in Palestine":
  facebook: "381320095930"
"Columbia Surgery":
  facebook: "78606477710"
"Columbia Technology Ventures":
  facebook: "94861973902"
"Columbia Undergraduate Film Productions - CUFP":
  facebook: "124992620889529"
"Columbia Undergraduate Law Review (CULR)":
  facebook: "170604546317524"
"Columbia University ACM":
  facebook: "110020189713"
"Columbia University AIChE Chapter":
  facebook: "520402061427273"
"Columbia University ASME":
  facebook: "1494887544128402"
"Columbia University Aikido Club":
  facebook: "296714777168407"
"Columbia University Amnesty International":
  facebook: "521503351319712"
"Columbia University Archives":
  facebook: "129297810427358"
"Columbia University Asian American Alliance":
  facebook: "148614427657"
"Columbia University Athletics":
  facebook: "102009214108"
"Columbia University Baha'i Club":
  facebook: "266583283465556"
"Columbia University Ballet Ensemble":
  facebook: "623118397733595"
"Columbia University Bhangra":
  facebook: "732370266883997"
"Columbia University Black Students' Organization":
  facebook: "66114979956"
"Columbia University Blue Key Society":
  facebook: "359273777483537"
"Columbia University Chinese Students Club (CSC)":
  facebook: "264877036963661"
"Columbia University Club Bangla":
  facebook: "154909354648149"
"Columbia University College Republicans":
  facebook: "114512668562658"
"Columbia University College of Dental Medicine":
  facebook: "123393449987"
"Columbia University College of Physicians and Surgeons":
  facebook: "126195220761399"
"Columbia University Dance Marathon":
  facebook: "468873433133028"
"Columbia University Department of Music":
  facebook: "255274897844489"
"Columbia University Environmental Biology Society":
  facebook: "560814647309204"
"Columbia University Ferris Reel Film Society":
  facebook: "128002713918422"
"Columbia University French Cultural Society":
  facebook: "235512743299366"
"Columbia University Gospel Choir":
  facebook: "266148036757553"
"Columbia University Institute of African Studies":
  facebook: "144606668914747"
"Columbia University Libertarians":
  facebook: "629861307054701"
"Columbia University Medical Center (CUMC)":
  facebook: "102771993129318"
"Columbia University National Undergraduate Film Festival":
  facebook: "101854429883634"
"Columbia University Performing Arts League - CUPAL":
  facebook: "386816071400756"
"Columbia University Renewable Energy Society":
  facebook: "638418239528605"
"Columbia University School of Continuing Education":
  facebook: "112695952113138"
"Columbia University School of General Studies":
  facebook: "29438666163"
"Columbia University School of Nursing":
  facebook: "91514290668"
"Columbia University School of Social Work":
  facebook: "108772683119"
"Columbia University Sewa":
  facebook: "366678636772770"
"Columbia University in the City of New York":
  facebook: "102471088936"
"Columbia University's Data Science Institute":
  facebook: "432008956893415"
"Columbia Women's Business Society":
  facebook: "183241131734731"
"Columbia Wushu":
  facebook: "125692804276829"
"Columbia | SIPA":
  facebook: "76561782869"
"Columbia: A Journal of Literature and Art":
  facebook: "142422209116916"
"Delta GDP - the Growth and Development Project at Columbia University":
  facebook: "276096035751148"
"Delta Gamma at Columbia University":
  facebook: "101366879910418"
"Engineers Without Borders-USA Columbia University":
  facebook: "156469054399404"
"Falun Dafa Club at Columbia University":
  facebook: "189854217716218"
"Hong Kong Students and Scholars Society - HKSSS":
  facebook: "496954750365809"
"Institute for Research in African-American Studies at Columbia University":
  facebook: "197174936966015"
"Middle East Institute at Columbia University":
  facebook: "150090971686018"
"Miller Theatre at Columbia University":
  facebook: "26916178394"
"Sundial":
  facebook: !!null
"The Blue and White":
  facebook: "567567480016627"
"The Caribbean Students' Association at Columbia University":
  facebook: "360462704017712"
"The Columbia Review":
  facebook: "330892190310554"
"The Columbia Undergraduate Science Journal":
  facebook: "233622070163726"
"The Federalist Columbia":
  facebook: "449856608476262"
"The Governing Board at Barnard College":
  facebook: "457753504323688"
"WICS Columbia":
  facebook: "741854835834184"
